identifier: claim-blocks
name: "&bClaim Blocks"
description:
  - "&eYou can buy claim blocks with this shop!"
takes:
  1:
    type: ITEM
    value: "material:emerald;amount:4;name:&7&k..&r &5&lSharded &2&lEmerith&r &7&k..;lore:<{\"text\":\"\\u00A7bUseful for getting more\"}>,<{\"text\":\"\\u00A77RTPs \\u00A7band \\u00A77Claim Blocks\\u00A78!\"}>;tags:shopItem:yes,serverItem:yes;enchantments:unbreaking:1;"
gives:
  1:
    type: GIVE
    value: "%random1,5%:stone{}"
